<a href="https://colab.research.google.com/github/neerajsingh4736/Deep-learning/blob/main/Intro_to_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print (torch.__version__)

2.2.1+cu121


Introduction to Pytorch


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
 #Get tensor back as Python int
scalar.item()


7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim


1

In [12]:
vector.shape

torch.Size([2])

In [17]:
# Matrix

MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
MATRIX[1]

tensor([ 9, 10])

In [42]:
# Tensor

tensor = torch.tensor([[[1,2,3],
                         [4,5,6],
                        [7,8,9],
                       ]])


In [43]:
tensor.shape

torch.Size([1, 3, 3])

In [39]:
tensor.ndim

4

In [35]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors


In [51]:
random_tensor = torch.rand(1,5,4)
random_tensor

tensor([[[0.9377, 0.9820, 0.4718, 0.8787],
         [0.0780, 0.8873, 0.2570, 0.1772],
         [0.0938, 0.0392, 0.5889, 0.1990],
         [0.6228, 0.8874, 0.1038, 0.0035],
         [0.7301, 0.0710, 0.5278, 0.0356]]])

In [52]:
random_tensor.ndim

3

### Image tensor
